### ISSUE TITLE
Don't check for ConfigureAwait in ASP.NET Core projects

### ISSUE THREAD

**Issue by cmeeren** [BigBabay/AsyncConverter#14]
According to [this post by Stephen Cleary](http://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html) (who literally wrote the book on async in .NET), there is no synchronization context in ASP.NET Core, and the ASP.NET Core team has dropped the use of `ConfigureAwait(false)`.

I therefore suggest that AsyncConverter does not check for ConfigureAwait in ASP.NET Core projects.

**Comment by BigBabay** [comment]
Hello.
Yes you can ignore ConfigureAwait(false) in your ASP.NET Core project. But if you will use a sharable library in an ASP.NET Core project you also can want to ignore ConfigureAwait(false) in this library too, but the AsyncConverterr plugin can't analyze it. Because of this, I consider that "Don't check for ConfigureAwait in ASP.NET Core projects" doesn't solves the problem.

But nevertheless you can configure every highlightings in a solution. You can just switch them off.
ReSharper=>Options=>Code Inspection=>Inspection Severity=>C#=>Async converter plugin=>Await not configured.

Also ReSharper allow you to have different settings per project.
https://blog.jetbrains.com/dotnet/2012/01/18/per-project-settings-or-how-to-have-different-naming-styles-for-my-test-project/

**Comment by cmeeren** [comment]
I'm not going to the trouble of specifying a custom R# settings layer just for this inspection setting, but thanks anyway for the suggestion and link. :)

**Comment by abdevnet** [comment]
Unfortunately this setting ReSharper=>Options=>Code Inspection=>Inspection Severity=>C#=>Async converter plugin=>Await not configured.

Does not effect code generation.  So if I convert a method to async I still get the proliferation of "ConfigureAwait(false)" statements.  Don't really want that in my asp.net core project.

**Comment by neuhausf** [comment]
@BigBabay could you add an option to (globally) disable adding `ConfigureAwait(false)`? I use this extension mainly in ASP.NET Core projects and here `ConfigureAwait(false)` doesn't make sense.
